Repository hashicorp/terraform-provider-http, pull requests merged in 2022-08, with the labels that each got.

#146 Allow optionally specifying HTTP request method and body
  CHANGELOG.md
  docs/data-sources/http.md
  go.mod
  go.sum
  internal/provider/data_source_http.go
  internal/provider/data_source_http_test.go
Labels: documentation, dependencies, size/L

#173 Bump expected minimum Go version to 1.18
  .github/workflows/test.yml
  .go-version
  DESIGN.md
  README.md
  go.mod
  go.sum
Labels: dependencies, size/M

#178 .github/workflows: Use upstream pr-size-labeler and ignore go.sum
  .github/workflows/pull-request.yml
Labels: size/XS

#180 Expand documentation to include HEAD and POST requests
  docs/data-sources/http.md
  examples/data-sources/http/data-source.tf
Labels: documentation, size/S
