Repository hashicorp/terraform-provider-http, pull requests merged in 2023-11, with the labels that each got.

#344 cdktf: update documentation
  docs/cdktf/python/data-sources/http.md
  docs/cdktf/python/index.md
  docs/cdktf/typescript/data-sources/http.md
  docs/cdktf/typescript/index.md
Labels: documentation, size/XS

#351 .github: Add CI for changie
  .github/workflows/ci-changie.yml
Labels: size/XS

#354 .github: Update workflows to use actions variables
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: size/S
