Repository hashicorp/terraform-provider-http, pull requests merged in 2023-03, with the labels that each got.

#242 Update release workflow to use service account PAT
  .github/workflows/release.yml
Labels: size/S

#245 Updating to Go 1.19
  .changes/unreleased/NOTES-20230303-150722.yaml
  DESIGN.md
  README.md
  go.mod
Labels: dependencies, size/XS, go

#248 .github/workflows: Test on Terraform 1.4.* versions
  .github/workflows/test.yml
Labels: size/XS

#249 Migrate acceptance tests to terraform-plugin-testing
  go.mod
  go.sum
  internal/provider/data_source_http_test.go
Labels: dependencies, size/XS, technical-debt
