Repository hashicorp/terraform-provider-http, pull requests merged in 2023-08, with the labels that each got.

#305 Adding Terraform 1.5.* to test matrix
  .github/workflows/test.yml
Labels: enhancement, size/XS

#314 cdktf: update documentation
  docs/cdktf/python/data-sources/http.md
  docs/cdktf/python/index.md
  docs/cdktf/typescript/data-sources/http.md
  docs/cdktf/typescript/index.md
Labels: documentation, size/S

#316 cdktf: update documentation
  docs/cdktf/python/data-sources/http.md
  docs/cdktf/python/index.md
  docs/cdktf/typescript/data-sources/http.md
  docs/cdktf/typescript/index.md
Labels: documentation, size/XS
