Repository hashicorp/terraform-provider-http, pull requests merged in 2025-03, with the labels that each got.

#504 chore: Update minimum Go version in module
  README.md
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: dependencies, size/S

#211 [fixes 254] Add mTLS support with client cert and key.
  docs/data-sources/http.md
  internal/provider/cert_test.go
  internal/provider/data_source_http.go
  internal/provider/data_source_http_test.go
Labels: documentation, dependencies, size/L

#514 Fix Windows acceptance tests by escaping backslashes so Terraform config is valid
  internal/provider/data_source_http_test.go
Labels: size/XS

#513 Prepare Release 3.5.0
  .changes/unreleased/FEATURES-20250331-114641.yaml
Labels: size/XS
