Repository hashicorp/terraform-provider-http, pull requests merged in 2025-04, with the labels that each got.

#523 cdktf: update documentation
  docs/cdktf/python/data-sources/http.md
  docs/cdktf/typescript/data-sources/http.md
Labels: size/XS

#516 Change release tooling to release with HashiCorp CRT
  .github/workflows/build.yml
  .release/ci.hcl
  .release/release-metadata.hcl
  .release/security-scan.hcl
  .release/terraform-provider-http-artifacts.hcl
  version/VERSION
Labels: size/XL

#528 chore: Final onboarding to CRT
  .copywrite.hcl
  .github/workflows/release.yml
  .goreleaser.yml
  README.md
Labels: size/L
